# https://github.com/marketplace/actions/deploy-to-github-pages
# based on https://github.com/bcgov/NotifyBC/blob/main/.github/workflows/ghPages.yml
name: Build and Deploy

on:
  [push]
  # push:
  #   branches:
  #     - main
  #   release:
  #     types:
  #       - published

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build # # This example project is built using npm and outputs the result to the 'build' folder.
        run: |
          cd docs
          make html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # folder the action should delopy
          clean: true
